Wait for MOTD before joining channels in irc bot
j0ack/discirc pull request #10
Opened 2017-10-27 19:50 UTC by tmarki

Hello,

your version does not work for the MOTD message, so on some IRC servers it fails to join any channels.

I fixed this by adding a callback for this, I hope you can merge it.

Thanks,
Tamas

2017-10-30 16:02 UTC, j0ack requested changes
Thanks for your work, just a little comment

2017-10-30 16:02 UTC, j0ack commented on discirc/irc_bot.py
> +    def on_motddone(self, message):
Could you just add a small docstring to the function ?
People may not understand what `motdone` is.

2017-10-30 16:17 UTC, tmarki commented
Added the docstring, I hope it's descriptive enough!

2017-10-31 01:35 UTC, TeoTwawki commented
@tmarki if I may make a suggestion:
```python
    """checking if Message Of The Day is done because it may interfere with joining channels"""
    def on_motddone(self, message):
```
Future editors then know both why clients should wait  and what motd is when they read the comment.

j0ack was concerned ppl wouldn't know what motd is.

2017-10-31 09:10 UTC, j0ack commented
I agree with @TeoTwawki, people may not know what `MOTD` stands for.

Just a little description as suggested would be great.

2017-10-31 09:36 UTC, tmarki commented
I replaced the docstring with your version.

2017-10-31 10:23 UTC, j0ack commented
Put the docstring behind the `def` and it will be fine for me.

Thanks for the work :)

2017-10-31 16:42 UTC, tmarki commented
Done!

2017-11-02 08:27 UTC, merged