Add support for password protected IRC channels
j0ack/discirc pull request #7
Opened 2017-01-21 10:49 UTC by TeoTwawki

2017-01-21 12:31 UTC, j0ack commented
Thank you for the PR, I make some comments on your code.

2017-04-14 06:54 UTC, j0ack commented
Are you still interested in this PR or should I implement my comments ?

2017-04-14 20:01 UTC, TeoTwawki commented
If you wanted something changed or there was a problem with it, you never actually told me so. The reply I received said only you intended to make some comments on my code. I assumed that meant you were reviewing it.

2017-04-18 13:19 UTC, j0ack commented
I actually did some comments in your code please tell me if you can't see it.

2017-04-18 13:20 UTC, j0ack commented on config-example.json
> +  },
I think you should inverse key and values here. It makes more sense if the password is the dict value and not the dict key imho.

2017-04-18 13:20 UTC, j0ack commented on discirc/irc_bot.py
> +                self.send('JOIN', channel=chan, key=self.channelPass)
Shouldn't it be `self.send('JOIN', channel=chan, key=key_extracted_from_channelPass)` ? 
In case you invert keys and values in your dict as suggested above you could do `self.channelPass[chan]`

2017-04-18 17:01 UTC, TeoTwawki commented
Amended but dunno if I got it right.

2017-04-19 06:58 UTC, j0ack requested changes
I think there is a mistake but after that I will merge the PR, thx

2017-04-19 06:58 UTC, j0ack commented on discirc/irc_bot.py
> +            if chan not in self.channelPass.values():
Since you invert keys and values in the config it should be 

`if chan not in self.channelPass`

2017-04-19 14:54 UTC, TeoTwawki commented
fix'd

2017-04-19 14:55 UTC, merged